### PR TITLE
Support CRA v4

### LINKED ISSUE #194: Does Not Work with CRA v4
With the release of [CRA v4](https://github.com/facebook/create-react-app/releases/tag/v4.0.0), this does not work anymore.

### PR DESCRIPTION
**Pull request by malcolm-kee**
resolves #194 

Support CRA v4. Non-breaking change.

### CODE REVIEW

**Comment by malcolm-kee** [comment]
@bahmutov mind to review the PR?

**Comment by bahmutov** [comment]
Sure and thank you - I will do it on Monday. I probably will plug in full examples into this repo to make sure code coverage is working for cra 3 and 4

**Comment by transmissions11** [comment]
Thanks for writing this PR @malcolm-kee was wondering why I couldn't start my project anymore!

**Comment by bahmutov** [comment]
Hi @malcolm-kee I appreciate your solution, and I have included it in the https://github.com/cypress-io/instrument-cra/pull/198 where I have added CI for react-scripts v4. I will close your PR, but will merge 198 to release this fix.

**Pull request closed without merging**
