### PR TITLE
feat: Add support for yarn workspaces

### LINKED ISSUE #25: Does not work with yarn workspaces
```
yarn run v1.15.2
$ react-scripts -r @cypress/instrument-cra start
internal/modules/cjs/loader.js:651
    throw err;
    ^

Error: Cannot find module '/monorepo/packages/my-react-app/node_modules/react-scripts/config/webpack.config.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (monorepo/node_modules/@cypress/instrument-cra/index.js:17:24)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
error Command failed with exit code 1.
```

This is looking for `node_modules/react-scripts/config/webpack.config.js`, but this file would actually exist higher up where `yarn workspaces` uses a single `node_modules` for all workspaces that use the same version of `react-scripts` as a dependency.

### PR DESCRIPTION
**Pull request by felixh10r**
Closes #25 

### User facing changelog

instrument-cra now works with yarn workspaces

### Additional details

For other projects it will fall back to the old behavior

### CODE REVIEW

**Review by bahmutov — APPROVED** [review]
nice!

**Comment by bahmutov** [comment]
@fhessenberger could you sign a CLA before I merge it, please?

**Comment by bahmutov** [comment]
@fhessenberger could you sign the CLA please, I cannot merge your PR before that

**Comment by felixh10r** [comment]
@bahmutov all set!

**Pull request merged**
